name: tg_pos_app
description: TG-SYSTEM Tablet POS Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  http: ^1.1.0
  
  # State Management
  provider: ^6.0.5
  
  # Local Storage (JWT)
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  
  # Utils
  intl: ^0.18.1 # 화폐 포맷팅
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true